access:
  free:
    - /user/authenticate
    - /user/login

menu:
  Administration:
    /user: Users

routes:
  /user: './cjs/user'
  /user/authenticate: './cjs/authenticate'
  /user/login: './cjs/login'
  /user/logout: './cjs/logout'
